### ISSUE TITLE
how to use my shape file

### ISSUE THREAD

**Issue by masabhathini** [adeckmyn/maps#13]
Hi,

I would like to use my own shape file in map() function.
can anybody guide me to create database of my shape file.
shape file is attached here.
[World-India.zip](https://github.com/adeckmyn/maps/files/2667336/World-India.zip)

Thanks & regards,
M. Sateesh
NCMRWF, India.

**Comment by adeckmyn** [comment]
Hi,
You can use any function that reads shapefile data into SpatialPolygon format:
z1=maptools::readShapePoly("india_map") # deprecated but still works
z2=rgdal::readOGD("india_map.dbf")

in both cases you can then do map(z1), map(z2).
Note that you may not be able to select regions/countries with the map() function.

Alex

**Comment by masabhathini** [comment]
z1=maptools::readShapePoly("/home/sateeshm/shapefiles/ncmrwf/india_map")
map(z1) 
Yes, Its working fine.
#########
Actually, I am struggling at here:
I am using openair package (https://github.com/davidcarslaw/openair)
In that, I am using trajLevel function. The plot is like below
![image](https://user-images.githubusercontent.com/25902165/49803849-00bb2380-fd77-11e8-80ed-473cb3983ca9.png)


Now, I would like to use my shape file instead of world. 


my sample code is below....
library(openair)
load("GDASNDL1000m.Rdata")
trajLevel(traj,method="hexbin",col="jet",xbin=40,parameters=NULL,orientation=c(90,0,0),projection="mercator")
[GDASNDL1000m.zip](https://github.com/adeckmyn/maps/files/2667752/GDASNDL1000m.zip)

Guide me, In this regard.
Thanks,

**Comment by adeckmyn** [comment]
sorry, I have no experience with that package. So you may be better off asking this e.g. on stackoverflow. If it is using the basic world map from 'maps' and you want to use another world map, there apparantly is no option to use a different map.You could make a plot without map and then plot your chosen map over it. Another option may be to replace the world map in such a way that opentraj wil use your own map by default. But that is hard, because I had a quick look at the source code of openair, and it is hard circumvent the hardcoded world map (the actual map plotting is in the function openair:::add.map). 

So except for adding the map separately, I see no simple way to do this other than modifying the function code itself to remove the hard coded map.

**Comment by masabhathini** [comment]
Thank you for your suggestions.
I will convey this to David (openair) also. 

Thank you

**Comment by masabhathini** [comment]
Dear Alex, 
ls /home/vishnu/GNU/R/R.3.4.3/lib64/R/library/maps/mapdata/world.*
How to create this world.G or .L or .N files with my shape data (z1)?
It may be the shortest way.

**Comment by adeckmyn** [comment]
Ooops. I missed this question 2 years ago. Just for the record, there are 2 solutions.  Very often you don't really need to create them at all. If you have a map object (as read from shapefile above), it can be used in the same way.
If you really want to create such .GLN files: I created the mapMaker package for manipulating the natural earth data. Not very user friendly, as it was mainly for personal use.
