### ISSUE TITLE
Problem with Loire regions in France

### ISSUE THREAD

**Issue by Zach-Fisherman** [adeckmyn/maps#22]
If I try to add only "Loire" to a region, it's gonna also add Loire, Loire-Atlantique, and Loiret to the map
Might have to do with the code searching for all regions starting with the same argument

here's the command I did : 
map(database="france",region=c("Loire"))

**Comment by adeckmyn** [comment]
This is normal behaviour (as explained in the man page), indeed because the code (by default) searches for all regions starting with "Loire". In this case, the simple solution is to add the option exact=TRUE, so you only fit the exact region name. If you wanted Loire and Loiret only, you could  even try a more sophisticated expression: "loire(?!-)", which will select Loire... except if followed by "-".

**Comment by Zach-Fisherman** [comment]
Thank you for your fast answer 👍
