### ISSUE TITLE
Custom Maps Packages

### ISSUE THREAD

**Issue by zachcp** [adeckmyn/maps#5]
HI @adeckmyn ,

Thanks for your maps and mapmaker packages. I've recently used your workflow to create a custom map package for [New York City](https://github.com/zachcp/nycmaps) but would like your thoughts on the best way to register the map.

I tried to follow the zzz.R file but had a bit of trouble being able to call maps so resorted to modifying my .GlobalEnv. I know thats a **no-no** so I was wondering if you have some thoughts on a good pattern for registering new map data.

``` r
# from zzz.R in nycmaps
.onLoad <- function(lib, pkg) {
  if (Sys.getenv("R_MAP_DATA_DIR") == "")
    Sys.setenv("R_MAP_DATA_DIR" = paste(lib, pkg, "mapdata/", sep="/"))
  ## temporarily, we add the possibility of changing for "world" only,
  ## to point at the /legacy subdirectory
  if (Sys.getenv("R_MAP_DATA_DIR_WORLD") == "") {
    if(Sys.getenv("R_MAP_DATA_LEGACY")=="TRUE") Sys.setenv("R_MAP_DATA_DIR_WORLD" = paste(Sys.getenv("R_MAP_DATA_DIR"), "legacy_",sep=""))
    else Sys.setenv("R_MAP_DATA_DIR_WORLD" = Sys.getenv("R_MAP_DATA_DIR"))
  }

  #include map libraries
  library.dynam("maps", "maps", lib)

  # set the environment to allow access to maps.
  # this is a bit clunky. is there a better way?
  Sys.setenv("NY_MAPS"= paste(lib, pkg, "mapdata/", sep="/"))
  Sys.setenv("nycMapEnv"="NY_MAPS")
  assign("nycMapEnv","NY_MAPS", envir = .GlobalEnv)
}
```

Thanks
zach cp

**Comment by adeckmyn** [comment]
Hi Zach,
I think you could simplify this a lot. The best example is maybe to look at the packages 'mapdata' (on CRAN) or 'mapdataNE' (on github). Similarly to nycmaps, they contains some extra maps.

The only entry in the R directory is zzz.R:

```
.onLoad <- function(lib, pkg){
Sys.setenv("R_MAPDATA_DATA_DIR"=paste(lib,pkg,"mapdata/",sep="/"))
}
```

All other stuff is already done by the maps package and there is no need to repeat it. Instead, you can make sure the basic maps package is launched automatically by setting it as a required package ("depends on") in the DESCRIPTION file. I think that is much cleaner and less disruptive than resetting some variables. It is perfectly possible to have several such map packages present together.

I see you want to assign the nycMapEnv variable in the .onLoad() function. That is not really the best way. If you just assign inside the environment of any function, it would not be visible to other functions. That's why you needed to assign explicitely to another environment. You should do it outside the .onLoad() {} function. Then it will be defined in the main environment of the nycmaps package.

So zzz.R could contain:

```
.onLoad <- function(lib, pkg){
Sys.setenv("NY_MAPS"=paste(lib,pkg,"mapdata/",sep="/"))
}
nycMapEnv <- "NY_MAPS"
```

In maps and mapdata, I just have simple assignments in the data directory (the .rda files were originally simple ascii .RData files containing an assignment). But I think this should work too.

hope this helps,
Alex

**Comment by zachcp** [comment]
Hi Alex,

Thanks for your well-written response. That was actually much easier than I realized!

Much obliged.
zach cp
