### ISSUE TITLE
non unique names in databases

### ISSUE THREAD

**Issue by mdsumner** [adeckmyn/maps#6]
I see 'world' and 'italy' have non unique values for 'names', which makes it hard to keep track of what parts belong to each "object".  

I haven't been comprehensive, just looked at a set of the dbs in the maps package below. The non unique values are listed at the end. 

Is it sensible to update and fix these manually? Are you interested to check the behaviour in mapdata and other dbs for this package generally? 

I want to be able to create 'sp' and 'ggplot2' types and other formats from these data sets, and so I'd like to know if my conclusion is correct before I continue. 

``` R
library(maps)  ## maps_3.1.1 from CRAN

getm <- function(nm) {
  map(nm, plot = FALSE, fill = TRUE)
}

dbs <- c("world", "usa", "state", "county", "france", "italy", "legacy_world", 
         "legacy_world2", "nz", "state.carto")
l <- vector("list", length(dbs))
for (i in seq_along(dbs)) {
  x <- getm(dbs[i])
  ## detect all NAs in coords
  bad <- is.na(x$x)
  ## count instances of NA (assume same for y)
  seqs <- sum(bad) + 1
  ## tabulate the unique sequences between the missing values
  ## (this is a check on whether there are runs of NA)
  counts <-   table((cumsum(bad) + 1)[!bad])
  ## the count of unique names
  nnames <- length(unique(x$names))
  l[[i]] <- data.frame(name = dbs[i], nseqs = seqs, ncounts = length(counts), 
                   names = nnames,
stringsAsFactors = FALSE)
}

do.call(rbind, l)

```

```
            name nseqs ncounts names
1          world   1627    1627  1625
2            usa     10      10    10
3          state     63      63    63
4         county   3085    3085  3085
5         france    114     114   114
6          italy    133     133   125
7   legacy_world   2284    2284  2026
8  legacy_world2   2284    2284  2026
9             nz     22      22    22
10   state.carto     50      50    50
```

```

## world
world <- map("world", fill = TRUE, plot = FALSE)
world$names[duplicated(world$names)]
#[1] "San Marino" "Vatican"  

## italy
italy <- map("italy", fill = TRUE, plot = FALSE)
italy$names[duplicated(italy$names)]
#[1] "Udine"         "Gorizia"       "Venezia"       "Venezia"       "Arezzo"       
#[6] "Avellino"      "Sassari"       "Caltanissetta"
```

I realize it's a different behaviour for fill = FALSE, but as far as I can see in that case the "names" vector is not useable, not related to the lists of NA-separated paths any more? Is that right?

**Comment by adeckmyn** [comment]
Thanks for bringing this to my attention.
By the way, I think the maptools package already has a function map2SpatialPolygons?

In the 'world'database, this is a relic of when I imported the NaturalEarth data set which is polygon-based. Vatican and San Marino are polygons of these countries, but they also exist in the database as boundaries of Italy (but drawn in opposite direction). Giving both versions the same name was a temporary solution which I then forgot about, I think. It's probably better to remove them completely. Strictly speaking they should be renamed Italy:San Marino or such for the internal boundaries of Italy, but then map(region="Italy") would always draw these tiny internal lines, which usually is not what people want. Since e.g. the two 'Vatican' polygons are identical except for the drawing direction, the double line doesn't really show up. But I'll look into removing them completely.

For the Italy map (which, to be honest, I'd never yet looked at since becoming maintainer), there's indeed some regions that are split into several polygons with the same name. You're right this is not a good idea. Probably it would be better to add a number (e.g. Venezia:1 ... Venezia:3) which is what I did in the new world data base (and e.g. in the spatialPolygon2map function I recently added). I'll have a look at it, but I must also be careful. The maps package has been around for many, many years and changing things may have an unexpected impact for some users.

Indeed, when fill=FALSE, the output is not organised as polygons but simply as lines. So the name vector is not very relevant. It's something I'd like to change, but it would involve major changes to the code and format, which I am a bit reluctant to do.

Some of the data sets in 'mapdata' don't even have decent polygon names, while worldHires is identical to legacy_world (only the resolution of the polylines is different).

**Comment by mdsumner** [comment]
great thanks, I'm aware of the maptools converters, but they are too restrictive - admittedly partly because of vagaries like this in the data though, so I'm keen to stamp out any problems rather than have workarounds (if possible).  

Oh (possible epiphany here!)  is the fill =FALSE lines output the unique "arcs"? (Rather than the duplicating the shared paths between polygons - I'll explore this. )

**Comment by adeckmyn** [comment]
Yes, fill=FALSE gives the non-duplicated "polylines". Most maps-databases are stored as lines and the polygons are described as sets of these lines. Some of the smaller maps are just polygons, though. Every polygon is just a single line in the database. But 'world' has no duplicated lines. Even the duplicated polygons like Vatican are just built from the same line. So fill=FALSE has no duplication (internally, it just builds the list of all numbered lines from the polygons and uses 'unique()'). There is some subtle difference when there are margins. With fill=TRUE the lines are left as they are, but with fill=FALSE they are cut at the map boundaries.

If such arcs are what you want, you may be interested in my package mapMaker. This is what I wrote to reformat the original NaturalEarth polygon data into non-duplicating lines. For the world map there was still a lot of manual work to correct things, but on smaller sets it works very well. 

On the other hand, the maps package data is not necessarily the best input data. There is now also a package rnaturalearth (on github, not yet on CRAN) which makes all data sets from Natural Earth available in sp format. As polygons, of course. Such SpatialPolygon data objects can also be readby the maps package, but it remains polygon data.

**Comment by mdsumner** [comment]
Thanks for the confirmation, it seems you could construct the polygons from the unique polylines by tracing shared vertices to neighbour polylines, then trace around the lines to detect cycles - but presumably it would be easier to preserve the list of which polylines belong to each polygon? 

I'm interested in data structures that can preserve this information, and treat other types like polygon-NA-sep-lists or sp as "special formats", generated as needed.   I'll definitely explore the arcs in mapMaker, this was a good learning exercise!  Spatial objects can be decomposed into "closed paths", using indexes into shared vertices - and that gives a stepping stone to topology, say for rgl plotting. Also having these arcs is something I want - either preserving them in the first place, or redetecting them from "simple features" etc. I've fleshed some of this out in my "gris" package, but that was overcomplicated and I'm working on a cleaner version, and much more explanation.
